import { UploadIcon, VideoIcon, ZapIcon } from 'lucide-react';

export const featuresData = [
    {
        icon: <UploadIcon className="w-6 h-6" />,
        title: 'Smart Upload & Analysis',
        desc: 'Easily upload your content and let our AI analyze it to extract key insights and optimize for maximum engagement.'
    },
    {
        icon: <ZapIcon className="w-6 h-6" />,
        title: 'Instant Content Generation',
        desc: 'Generate high-quality, engaging content in seconds with our AI-powered tools, designed to resonate with your audience.'
    },
    {
        icon: <VideoIcon className="w-6 h-6" />,
        title: 'Video Synthesis & Enhancement',
        desc: 'Transform your static images into dynamic, high-quality videos with our AI-powered video synthesis and enhancement tools.'
    }
];

export const plansData = [
    {
        id: 'starter',
        name: 'Starter',
        price: '$10',
        desc: 'Try the platform at no cost.',
        credits: '25 credits',
        features: [
            '25 AI credits per month',
            'Standard quality content',
            'No watermark',
            'Slower generation speed',
            'Email support'
        ]
    },
    {
        id: 'pro',
        name: 'Pro',
        price: '$29',
        desc: 'Creators and small teams.',
        credits: '80 credits',
        features: [
            '80 AI credits per month',
            'HD content generation',
            'No watermark',
            'Video generation',
            'Priority support'
        ],
        popular: true
    },
    {
        id: 'ultra',
        name: 'Ultra',
        price: '$99',
        desc: 'Scale across teams and agencies.',
        credits: '300 credits',
        features: [
            '300 AI credits per month',
            'FHD content generation',
            'No watermark',
            'Advanced video generation',
            'Chat + Email support'
        ]
    }
];

export const faqData = [
    {
        question: 'How does the AI content generation work?',
        answer: 'Our platform uses advanced machine learning algorithms to analyze your input and generate high-quality content that matches your style and audience preferences.'
    },
    {
        question: 'Do I own the content created by the AI?',
        answer: 'Yes, all content generated by our AI is owned by you. We do not retain any rights to the content you create using our platform.'
    },
    {
        question: 'Can I cancel my subscription at any time?',
        answer: 'Yes - you can cancel from your dashboard. You will retain access through the end of your billing cycle, but you will not be charged for the next month.'
    },
    {
        question: 'What input formats do you support for content generation?',
        answer: 'We accept JPG, PNG and WEBP. Outputs are generated high-resolution JPGs and MP4 optimized for social media sharing.'
    }
];

export const footerLinks = [
    {
        title: "Quick Links",
        links: [
            { name: "Home", url: "#" },
            { name: "Features", url: "#" },
            { name: "Pricing", url: "#" },
            { name: "FAQ", url: "#" }
        ]
    },
    {
        title: "Legal",
        links: [
            { name: "Privacy Policy", url: "#" },
            { name: "Terms of Service", url: "#" }
        ]
    },
    {
        title: "Connect",
        links: [
            { name: "Twitter", url: "#" },
            { name: "LinkedIn", url: "#" },
            { name: "GitHub", url: "#" }
        ]
    }
];